// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIndicators(arg1, arg2) {
  return window['go']['main']['App']['GetIndicators'](arg1, arg2);
}

export function GetMarketData(arg1, arg2) {
  return window['go']['main']['App']['GetMarketData'](arg1, arg2);
}

export function StartMarketDataStream(arg1, arg2) {
  return window['go']['main']['App']['StartMarketDataStream'](arg1, arg2);
}

export function StopMarketDataStream(arg1) {
  return window['go']['main']['App']['StopMarketDataStream'](arg1);
}
