// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeTestData(arg1) {
  return window['go']['main']['App']['AnalyzeTestData'](arg1);
}

export function GetAlertSignals(arg1, arg2) {
  return window['go']['main']['App']['GetAlertSignals'](arg1, arg2);
}

export function GetAlerts(arg1) {
  return window['go']['main']['App']['GetAlerts'](arg1);
}

export function GetIndicators(arg1, arg2) {
  return window['go']['main']['App']['GetIndicators'](arg1, arg2);
}

export function GetMarketData(arg1, arg2) {
  return window['go']['main']['App']['GetMarketData'](arg1, arg2);
}

export function GetMarketPrice(arg1, arg2) {
  return window['go']['main']['App']['GetMarketPrice'](arg1, arg2);
}

export function GetNetworkLogs(arg1) {
  return window['go']['main']['App']['GetNetworkLogs'](arg1);
}

export function InitDatabase(arg1) {
  return window['go']['main']['App']['InitDatabase'](arg1);
}

export function LoadTestData(arg1) {
  return window['go']['main']['App']['LoadTestData'](arg1);
}

export function ProxyAPI(arg1, arg2) {
  return window['go']['main']['App']['ProxyAPI'](arg1, arg2);
}

export function StartAutoSync(arg1, arg2) {
  return window['go']['main']['App']['StartAutoSync'](arg1, arg2);
}

export function StartMarketDataStream(arg1, arg2) {
  return window['go']['main']['App']['StartMarketDataStream'](arg1, arg2);
}

export function StartPrioritySync() {
  return window['go']['main']['App']['StartPrioritySync']();
}

export function StopAutoSync(arg1) {
  return window['go']['main']['App']['StopAutoSync'](arg1);
}

export function StopMarketDataStream(arg1) {
  return window['go']['main']['App']['StopMarketDataStream'](arg1);
}

export function SyncKlineData(arg1) {
  return window['go']['main']['App']['SyncKlineData'](arg1);
}

export function SyncKlineDataInitial(arg1, arg2) {
  return window['go']['main']['App']['SyncKlineDataInitial'](arg1, arg2);
}

export function TestBollingerHammerAlert(arg1) {
  return window['go']['main']['App']['TestBollingerHammerAlert'](arg1);
}
