// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlertSignals(arg1:string,arg2:string):Promise<string>;

export function GetIndicators(arg1:string,arg2:string):Promise<string>;

export function GetMarketData(arg1:string,arg2:string):Promise<string>;

export function InitDatabase(arg1:string):Promise<string>;

export function StartAutoSync(arg1:string,arg2:number):Promise<string>;

export function StartMarketDataStream(arg1:string,arg2:string):Promise<void>;

export function StopAutoSync(arg1:string):Promise<string>;

export function StopMarketDataStream(arg1:string):Promise<void>;

export function SyncKlineData(arg1:string):Promise<string>;

export function SyncKlineDataInitial(arg1:string,arg2:number):Promise<string>;
