// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIndicators(arg1:string,arg2:string):Promise<string>;

export function GetMarketData(arg1:string,arg2:string):Promise<string>;

export function StartMarketDataStream(arg1:string,arg2:string):Promise<void>;

export function StopMarketDataStream(arg1:string):Promise<void>;
